### ISSUE TITLE
Iterator send empty link in HTTPS module, when the next page does not exist

### ISSUE THREAD

**Issue by lightcomc** [bramkn/n8n-nodes-iterator#3]
**Iterator sends empty next page to the HTTP module** when the next page does not exist and we get an error that the link does not exist and the HTTPS model cannot handle the request.
![Image 2931](https://user-images.githubusercontent.com/111423897/201471471-8e5113e9-ade8-4239-9fba-0fb3334097af.png)

Result contains 2 pages, The script gets stuck when the iterator keeps sending an empty value to the HTTP module instead of checking if it exists or not (and sending the results to Done).
![Image 2933](https://user-images.githubusercontent.com/111423897/201471497-6de73f14-31f7-4eb6-82e2-e10d308e795d.png)

Iterator parameters
![Image 2934](https://user-images.githubusercontent.com/111423897/201471498-736cf63e-9f67-477e-a674-cbabd929159d.png)

2nd page (Iterated)
![Image 2935](https://user-images.githubusercontent.com/111423897/201471499-4500520f-f39b-436b-af60-a3105eee8602.png)

Parameters
Iterator Module - Reference Start: https://xxx/api/v4/events?filter[created_at][from]=1666795337&filter[created_at][to]=1666795338&limit=100
 Iterator Module - Reference Next (Taken from a HTTP module): {{$node["HTTP Request"].json["_links"]["next"]["href"]}}
HTTP REQUEST MODULE - {{$node["Iterator"].context["currentReference"]}}

What should I do so that it collects all the values and sends them to Done, as is done in the example:
https://community.n8n.io/t/new-community-node-iterator/17741

Thanks for the help, I think we can get a very powerful tool by fine-tuning the module, I have 200,000 records and they are processed 100 at a time, such a method would make the task a lot easier.

**Comment by bramkn** [comment]
Hi there,

There is an option you can add to tell it when to stop. Which you can let check to see if there is a next page. Not at a pc at the moment, so cannot give you an example right now.
Please check the options and let me know if you were able to fix it.

**Comment by lightcomc** [comment]
![image](https://user-images.githubusercontent.com/111423897/201498205-f6b513c3-af0d-4771-811b-8e5c4053bb8d.png)

Is There Another Page option - Made it active, started it up. No success

**Comment by bramkn** [comment]
You need to create an expression to handle that.

**Comment by lightcomc** [comment]
How to do that to send in DONE route?

My workaround is a create iF node to check empty value, between modules, that helps me once
![image](https://user-images.githubusercontent.com/111423897/201516491-52da1e9f-4d68-4913-9ac7-f9e52e2ed18a.png)

**Comment by bramkn** [comment]
I checked the code for ya.
There is a bug. And it cannot be used properly.
You can do 2 things.

have a set node before the iterator setting the value to true with an expression.
and then have it check the next page in the loop to set it true or false.

another thing you can do is use the Expected item count option.

**Comment by lightcomc** [comment]
Thank you very much, i understand what to do

**Comment by lightcomc** [comment]
![image](https://user-images.githubusercontent.com/111423897/201518370-064f06ea-f891-4b60-8adf-01ee1a6418c3.png)
IF module between iterator  and Http moule works as expected. domain is expected link / main (.com) address of the link 
IF empty - ended

**Comment by bramkn** [comment]
![image](https://user-images.githubusercontent.com/74856333/201522814-1c8d3cef-e2bc-427c-9a42-135529cf3293.png)
Does seem to work though, guess I saw something wrong in the code. Didn't have my coffee yet.

**Comment by bramkn** [comment]
@lightcomc I've updated the package to version 1.2
Did some fixes and added some small features.
should now work easily for you, as it does not check the option "Is there another page" in the first iteration anymore. So you can easily set that to the next field to see if it exists.

**Comment by lightcomc** [comment]
https://xxx/api/v4/events?filter[created_at][from]=1666795339&filter[created_at][to]=1666795340&limit=100
Iterate branch reference start not sending any info to next module afer update (grey), strange. and not send if options "here is another page" of "combine" is checked.
![image](https://user-images.githubusercontent.com/111423897/201541397-3b8c1724-b588-41fa-8a8b-face1db6699e.png)


![image](https://user-images.githubusercontent.com/111423897/201541225-e17e5ce5-7c0a-444c-893e-c8b149daa6f1.png)

Maybe i do something wrong. restart n8n not helps. latest n8n.
I have a feeling it's about to become awesome.

after all
created rollback via n8n-nodes-iterator@0.1.1 in Community nodes section.

**Comment by bramkn** [comment]
You have to be more clear about what you are doing.

**Comment by bramkn** [comment]
the max iterations is causing an issue here. setting it to 9999999 would solve it.

**Comment by lightcomc** [comment]
Yes, I haven't set a maximum number of iterations, perhaps this will help. 

I went back to the old method with IF and it works fine too, solves my problem. 

There's a lot of amount there. N8N is super tool, much more flexible in some aspects of the "make" service, but harder to master.

**Comment by lightcomc** [comment]
Updated to v0.1.2
There is no such option - max iterations 
![image](https://user-images.githubusercontent.com/111423897/201852902-c873de36-82c0-45cd-afdb-2eb2160e8305.png)

**Comment by bramkn** [comment]
Then you didnt update or didnt reboot the server. I am using it myself so I know it is there 😅

**Comment by lightcomc** [comment]
hard reboot heal all questions, wow it works!

**Comment by lightcomc** [comment]
I checked new version. 

If there are a certain number of iterations, the script works perfectly - it works and makes combine elements and it is really easy to work with this information.
![image](https://user-images.githubusercontent.com/111423897/201997586-f50d9a73-3605-4f99-a281-380bef7235e5.png)
Perfect!


My situation is a bit strange. 
A query for 10 iterations may yield 0 pages - this is sent straight to the end of the script. and up to 15 pages (some iterations yield up to 2 pages)

![image](https://user-images.githubusercontent.com/111423897/201994019-0d9c7b82-4eed-4369-ad52-5f2ce3e79cc9.png)

I have the "old IF" check for no page, but it outputs values from only  the last iteration. 



My settings
![image](https://user-images.githubusercontent.com/111423897/201995442-d42edefa-7306-4bcf-9652-517f788d2e84.png)

If the boolean value "Is There Another Page" is additionally active, this also works as described above


It would be ideal to check if there is a page (2 and... page) in incoming data from HTTPS module. If in "Reference Next" is no page - make combine and send all values to Done

**Comment by lightcomc** [comment]
I checked my case, found a solution to limit the number of iterations issued to one.
One second gives out 1 to 2 pages (2 iterations max). So if there is a second page it is sent to done, if there is only one page it goes via IF empty and works the same as done.  
I would of course like to be able to output more data to the handler, but this is enough to be successful. But it will work autonomously.

**Comment by bramkn** [comment]
Sorry it is a lot to take in, have no idea what you are talking about. :-)

**Comment by lightcomc** [comment]
problem in incoming data from HTTPS module. 

"Reference Next" no check empty page value. iterate, when next page is empty.
There is no way to stop and combine when page value from HTTPS module is empty.

**Comment by lightcomc** [comment]
> ![image](https://user-images.githubusercontent.com/74856333/201522814-1c8d3cef-e2bc-427c-9a42-135529cf3293.png) Does seem to work though, guess I saw something wrong in the code. Didn't have my coffee yet.

Oh i forgot about this one. Fantastic - it works! 
My case - add expression in "Is There Another Page" - {{$node["HTTP Request"].json["_links"]["next"]["href"]!== null}}
![image](https://user-images.githubusercontent.com/111423897/202272069-21008bc2-962f-41a5-b6f4-98cb10cb2703.png)


Wonderful! many thanks for support [bramkn](https://github.com/bramkn) 🤝

**Comment by lightcomc** [comment]
It works before 1x version, now first run with error

✅ Is There Another Page
{{$node["HTTP Request8"].json.body.next_page_token !== null}}

ERROR: no data, execute "HTTP Request8" node first
without this check - work as needed

![image](https://github.com/bramkn/n8n-nodes-iterator/assets/111423897/32857e9b-7b41-4f48-b43e-0a56b67f772c)

**Comment by bramkn** [comment]
That is probably because n8n doesn't accept invalid expressions anymore.
So you will have to fix that. ;-)

**Comment by bramkn** [comment]
also you are responding to a closed issue which isn't the best ;-)

**Comment by lightcomc** [comment]
> also you are responding to a closed issue which isn't the best ;-)
Thank you very much for this product
