### ISSUE TITLE
Does not seem to loop

### ISSUE THREAD

**Issue by trijste** [bramkn/n8n-nodes-iterator#6]
I'm trying to set this up to use with the HubSpot API, which uses an offset for paging. The initial request is passed through iterator to the looped request, but no subsequent requests pass and it exits after the first pass.

<img width="1111" alt="CleanShot 2023-04-15 at 12 58 05@2x" src="https://user-images.githubusercontent.com/23725702/232239578-b4d11f2a-34b7-43b1-b153-b37ccc705a59.png">

What am I missing here?

<img width="656" alt="CleanShot 2023-04-15 at 12 59 56@2x" src="https://user-images.githubusercontent.com/23725702/232239702-d175315e-51e6-400c-bd5b-8b89d67cacc2.png">

<img width="651" alt="CleanShot 2023-04-15 at 13 00 54@2x" src="https://user-images.githubusercontent.com/23725702/232239835-58b19859-fbda-43f0-bcda-fdb85e4c2135.png">

<img width="647" alt="CleanShot 2023-04-15 at 13 02 13@2x" src="https://user-images.githubusercontent.com/23725702/232240051-a399c2c6-047b-4001-b4c5-1e05e39af318.png">

**Comment by bramkn** [comment]
Try setting the limit and expected count as fixed values

Op za 15 apr. 2023 19:03 schreef trijste ***@***.***>:

**Comment by trijste** [comment]
Hi @bramkn, thank you for your help. I changed to fixed values but got the same result. Nothing passes to the http request node from the iterate node on the second pass.

The Loop Request returns 50 offset to the iterator:
<img width="1026" alt="CleanShot 2023-04-15 at 16 26 30@2x" src="https://user-images.githubusercontent.com/23725702/232251822-65ce56d7-505a-4dc4-b57a-c98d9ff7d23c.png">

The iterator node returns no data:
<img width="1027" alt="CleanShot 2023-04-15 at 16 27 36@2x" src="https://user-images.githubusercontent.com/23725702/232251864-e4fd5d0a-27d5-4edb-b4b7-c3db49ebb9cf.png">

**Comment by bramkn** [comment]
The HTTP node is returning 1 item (probably an array of data) if you split that before the iterator it should work. As now you get 1 item and it wants 50 (as you set that)

**Comment by trijste** [comment]
Thank you. I understand my confusion there now. I can loop, but I cannot iterate on the increment (50) so that the offset works sequentially through the total records from the initial query.

Is this expected?
<img width="289" alt="CleanShot 2023-04-15 at 17 40 16@2x" src="https://user-images.githubusercontent.com/23725702/232254301-c9148308-52eb-449d-a9c6-6830ca6cf17a.png">

**Comment by trijste** [comment]
I think I need to set an offset value outside of where I collect the items to return to the iterator... Maybe I should step away for a bit

**Comment by bramkn** [comment]
Sorry, have no idea what you are doing.
The iterator is meant to simply iterate over pages and such. Simply doing +1 for every iteration for example. 
Setting the values as expressions will mess this up, as they should be static fields.

**Comment by trijste** [comment]
Thanks for your time. I couldn't figure out Iterator probably because I wasn't looking at it with a fresh enough mind. I ended up using this:

<img width="1061" alt="CleanShot 2023-04-16 at 13 02 20@2x" src="https://user-images.githubusercontent.com/23725702/232328468-0cfa7ebc-fe18-46d0-85c8-0c76a1424fed.png">

The Offset Increment Code node uses this:

```
let currentValue = parseInt($node["Set"].json["offset"]) || 0;
const incrementValue = 50;

currentValue += incrementValue;

return {
  json: {
    currentValue: currentValue
  }
};
```

The Count Code node uses this:

```
if (Object.keys(items[0].json).length === 0) {
  return [
     {
       json: {
         results: 0,
       }
      }
  ]
}
return [
  {
    json: {
      results: items.length,
    }
  }
];
```

Off the top, I set the offset variable to reference the Offset Increment node, which is 0 unless encountered in the loop. I set the offset variable in the HTTP request node to reference the Set node. When the request is processed, If the Count result is less than the offset, the loop ends, otherwise the offset increment node adds the limit value to the offset (50) and passes that into the Set node to form the loop.

I would be curious to know how to achieve the same thing with Iterator.

Thanks again!

**Comment by bramkn** [comment]
Hi @trijste 

Sorry, only now noticed you are using an offset of 50 for your http request.
The increment size should be set to 50 and starting at 0
This should increment it for 0,50,100 etc.
the workflow should look like this:
![image](https://user-images.githubusercontent.com/74856333/232331868-abb59fa5-374c-4086-9e5d-73a2aa27b530.png)
Iterator like this:
![image](https://user-images.githubusercontent.com/74856333/232331908-9bcc81a4-69c1-4963-8e37-bf048aa9b6cc.png)

**Comment by trijste** [comment]
Hey thanks for that! So in the HTTP request then, the offset is set as the incoming variable from the Iterator node?

**Comment by bramkn** [comment]
You then set the current increment from the context of the iterator node as the offset in the http request.

**Comment by trijste** [comment]
I was able to get it working, and I very much appreciate your time and your help.
